### ISSUE TITLE
Add "Recent and Rapid" column to Clusters tab

### ISSUE THREAD

**Issue by stevenweaver** [veg/hivtrace-viz#11]
- [x] Recent and Rapid column should be ranked by number of nodes that are within 0.5% distance of each other and has an attribute of ascertainment within the last 12 months.
- [x] A "priority"  cluster (one of which that should be of primary interest to the researcher) is any cluster that has had more than three new nodes within the last year based on the date of ascertainment. Priority cluster rows should be highlighted. 
- [x] A button should be made available for viewing the cluster with specialized Recent and Rapid visualizations.

**Comment by spond** [comment]
Initial implementation in e4678932cc318ff23337c5a02071619487272beb
