### ISSUE TITLE
Create "Recent and Rapid" cluster visualization

### ISSUE THREAD

**Issue by stevenweaver** [veg/hivtrace-viz#12]
- [x] Display nodes that are a part of Recent and Rapid subclusters and nodes that are adjacent (one degree of separation to nodes in R&R subclusters).
- [x] Color nodes according to relation. (Blue outline for nodes that are younger than 12 months, red for nodes that are more generally part of R&R). A recommendation was made that edges be highlighted instead. Agreement was reached to leave to developer discretion. 
- [x] An export link for saving the SVG as a PNG
- [ ] A link that exports cluster information to CSV. (Node ID, Distance, Cluster Name, Subcluster Name)
- [ ] [Optional] Allow saving of clusters at different thresholds. 

_Note - In an effort to minimize complexity, the Recent and Rapid view should be completely separate from the current cluster visualization._

**Comment by spond** [comment]
Partial implémentation in e4678932cc318ff23337c5a02071619487272beb
