### ISSUE TITLE
error when run `yarn develop`?

### ISSUE THREAD

**Issue by liamxg** [veg/hivtrace-viz#120]
$yarn develop
yarn run v1.22.21
error hivtrace-viz@1.1.1: The engine "node" is incompatible with this module. Expected version ">=17 <20". Got "10.15.0"
error Commands cannot run with an incompatible environment.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by stevenweaver** [comment]
Yes, please use `node` versions 17, 18, or 19. Consider using `nvm` or `volta` to manage `node` versions. 

Best,
Steven

**Comment by stevenweaver** [comment]
Try `yarn` then `yarn develop`

**Comment by stevenweaver** [comment]
@liamxg -- that's very much by design. Please see https://github.com/veg/hivtrace-viz/issues/120#issuecomment-1813783956
