### ISSUE TITLE
"Show small clusters" checkbox misbehaving

### ISSUE THREAD

**Issue by nathanosman** [veg/hivtrace-viz#15]
Hi,

this is a minor misbehavior, the checkbox "Show small clusters" doesn't reset if previously checked when loading a new file to visualize, meaning that to show small clusters from the new file, the box has to be unchecked.

Thank you for your consideration.
Regards,
Nathan

**Comment by stevenweaver** [comment]
Dear @nathanosman, 

Thank you for pointing this out! It should be fixed in the next release. 

Best,
Steven
