### ISSUE TITLE
Merge March updates

### ISSUE THREAD

**Issue by spond** [veg/hivtrace-viz#2]
Dear @stevenweaver,

Could you please prioritize merging all the recent updates to the viz from my branch into the viz repo? I anticipate doing some further work on it soon, and also need to have a version deployed for the UCSD PIRC database. Having an up-to-date master repo for the viz would be very handy, and avoid future manual merges.

Best,
Sergei

**Comment by spond** [comment]
Thank you!

**Comment by stevenweaver** [comment]
Please let me know if everything made it in alright. I came across a conflict while merging, and I wasn't exactly sure what changes to look for.
