### ISSUE TITLE
"Show sequences in cluster"

### ISSUE THREAD

**Issue by stevenweaver** [veg/hivtrace-viz#20]
Dear Sergei, 

I apologize, I should have taken a closer look before merging, but these are the two issues I've come across. 

- [ ] The "Show sequences in cluster" menu option appears to be for debugging purposes, can you confirm that is the case?

- [ ] Prevalence is required by clusternetwork.js but never called. I believe I know what this feature is, but if you have an updated version of clusternetwork.js with the call to prevalence, it may be best.

**Comment by spond** [comment]
Dear @stevenweaver,

"Show sequences in cluster" is TBI. For the time-being it should be commented out.

I was incorrect in my previous message: prevalence.js is **not** being used; I rolled the new functions into "misc.js". Therefore you can go ahead and remove the `require` and `prevalence.js` files.

Best,
Sergei
