### ISSUE TITLE
Error after loading .json network file

### ISSUE THREAD

**Issue by nathanosman** [veg/hivtrace-viz#27]
Good afternoon,

I have been using https://veg.github.io/hivtrace-viz/ to visualize the networks I build using hivtrace installed on a local computer, it used to work well, but lately I have the error

> Network loading failed with the following error TypeError: Cannot read property 'length' of undefined

displayed, although the proper number of clusters, nodes and links show in the top right corner.

How can I solve this issue?

Thank you very much.
Regards,
Nathan

**Comment by stevenweaver** [comment]
Dear @nathanosman, 

There was a leftover development option that was left on during a big development push. I've resolved this specific issue and you should be able to load the network now.

Best,
Steven

**Comment by nathanosman** [comment]
Dear @stevenweaver,

It works now, thank you very much.

Regards,
Nathan
