### ISSUE TITLE
Add new min-width and min-height options

### ISSUE THREAD

**Issue by stevenweaver** [veg/hivtrace-viz#37]

**Comment by stevenweaver** [comment]
This is the part of the code that should be configurable. 

https://github.com/veg/hivtrace-viz/blob/80cea247dbd89151a57448c1a504c7eb38fc3782/src/clusternetwork.js#L1982

**Comment by rdvelazquez** [comment]
Addressed by https://github.com/veg/hivtrace-viz/commit/9dd15ecc0409e4bf023e6e64b3cbe17de89bac38
