### ISSUE TITLE
Flag attributes with no variance from dropdown menu lists on Network tab

### ISSUE THREAD

**Issue by stevenweaver** [veg/hivtrace-viz#56]
![image](https://user-images.githubusercontent.com/535261/70357152-34bf0c80-1844-11ea-8eae-05d46bdfe1ae.png)

**Comment by spond** [comment]
Dear @stevenweaver,

Hide or flag? 

Best,
Sergei

**Comment by stevenweaver** [comment]
Dear @spond,

I've updated the issue to flag as opposed to hide. 

Thank you for your feedback, 
Steven

**Comment by stevenweaver** [comment]
Resolved
