### ISSUE TITLE
Add "Filtered Nodes" field to Network Summary page

### ISSUE THREAD

**Issue by stevenweaver** [veg/hivtrace-viz#68]
In order to ensure that the number of nodes in the Summary page add up to the initial number of sequences submitted, we should add a `Filtered Nodes` row, alongside the reason why it was filtered, in the Network Summary tab.

**Comment by spond** [comment]
Dear @stevenweaver,

Great find. Do you want to do it, or should I?

Best,
Sergei

**Comment by stevenweaver** [comment]
Dear @spond,

Because it requires tweaking to the `hivtrace` pipeline to feed known contaminants to `hivnetworkcsv`, it is likely that I'm best suited for this task, but I appreciate your willingness to help. 

Best,
Steven

**Comment by spond** [comment]
Dear @stevenweaver,

The less work for me the better! I am past ready to rest on my academic laurels. 

Best,
Sergei
