### ISSUE TITLE
How to define the color of each node？

### ISSUE THREAD

**Issue by Omnipotent32** [veg/hivtrace-viz#72]
Hi, I'm very interested in HIV-TRACE. I tried to use 117 CRF07_BC pol sequences named as "07BC_2016_MSM_F" style to identify clusters. Unfortunately, when I import the json file outputted by HIV-TRACE( performed on Ubuntu 18.4 LTS) into visualization webpage, the color and shape of the nodes can not defined like what it can do in online edition ( Datamonkey).  however, when I downloaded and imported the example json file in, there's many options of color and shape can be done with the nodes. Would anyone please tell me if I miss some step to operated with json file outputted directly by HIVTRACE? I tried to load CSV annotation file, but whenever I load the CSV file, the webpage would become grey and with no reaction.

**Comment by stevenweaver** [comment]
Dear @Omnipotent32, 

There are two portions of the output JSON you may want to verify are being populated. 


For example, in example.json, you need to see something like this:

```
    "patient_attribute_schema": {
      "_id": {
        "type": "ObjectID"
      },
      "age": {
        "label": "age",
        "type": "String"
      },
      "birth_sex": {
        "enum": ["Male", "Female", "", "Missing"],
        "label": "sex",
        "type": "String"
      },
      "cur_city_fips": {
        "label": "cur_city_fips",
        "type": "String"
      },
      "cur_city_name": {
        "label": "cur_city_name",
        "type": "String"
      },
      "cur_county_fips": {
        "label": "cur_county_fips",
        "type": "String"
      },
      "cur_county_name": {
        "label": "cur_county_name",
        "type": "String"
      },
      "cur_state_cd": {
        "label": "cur_state_cd",
        "type": "String"
      },
      "ehars_uid": {
        "label": "ehars_uid",
        "type": "String"
      },
      "hiv_aids_dx_dt": {
        "label": "hiv_aids_dx_dt",
        "type": "Date"
      },
      "race": {
        "enum": [
          "Native Hawaiian/Other Pacific Islander",
          "American Indian/Alaska Native",
          "Other",
          "Asian",
          "Black/African American",
          "White",
          "Hispanic/Latino",
          "Multiple Races",
          "Unknown",
          "",
          "Missing"
        ],
        "label": "race_cat",
        "type": "String"
      },
      "rsd_county_fips": {
        "label": "rsd_county_fips",
        "type": "String"
      },
      "rsd_county_name": {
        "label": "rsd_county_name",
        "type": "String"
      },
      "rsd_state_cd": {
        "label": "rsd_state_cd",
        "type": "String"
      },
      "sample_dt": {
        "label": "sample_dt",
        "type": "Date"
      },
      "starhs": {
        "enum": ["1-AIDS0", "5-MISSING", "", "Missing"],
        "label": "starhs",
        "type": "String"
      },
      "trans_categ": {
        "enum": [
          "MSM",
          "IDU-Male",
          "Heterosexual Contact-Male",
          "Other-Male",
          "IDU-Female",
          "Heterosexual Contact-Female",
          "Other-Female",
          "Perinatal",
          "Other-Child",
          "",
          "Missing"
        ],
        "label": "sex_trans",
        "type": "String"
      },
      "vital_status": {
        "enum": ["1-Alive", "2-Dead", "9-Unknown", "", "Missing"],
        "label": "vital_status",
        "type": "String"
      },
      "vl_recent_dt": {
        "label": "vl_recent_dt",
        "type": "Date"
      },

      "result_interpretation": {
        "label": "result_interpretation",
        "type": "String",
        "enum": ["=", "<", ">", "Missing"]
      },

      "vl_recent_value": {
        "label": "vl_recent_value",
        "type": "Number"
      }
    }
  }
```

Then, for each node, an example like the following:

```
   {
        "attributes": [],
        "baseline": null,
        "cluster": null,
        "edi": null,
        "id": "GA00S000165129-0",
        "patient_attributes": {
          "_id": "5845cf134c554ab1d9657dfc",
          "age": "20-29",
          "birth_sex": "",
          "cur_city_fips": "04000",
          "cur_city_name": "ATLANTA",
          "cur_county_fips": "089",
          "cur_county_name": "DEKALB CO.",
          "cur_state_cd": "Georgia",
          "ehars_uid": "GA00S000165129-0",
          "hiv_aids_dx_dt": "1970-01-01T05:35:41.031Z",
          "race": "",
          "rsd_state_cd": "Georgia",
          "sample_dt": "2016-08-08T07:00:00.000Z",
          "starhs": "",
          "trans_categ": "",
          "vital_status": "1-Alive",
          "vl_recent_value": 453,
          "result_interpretation": "="
        }
      }
```

To do this programmatically, you need to use the `-g` argument to pass a patient_attribute_schema.json file formatted like
```
{
  "age": {
    "type": "String",
    "label": "age_dx"
  },
  "ehars_uid": {
    "type": "String",
    "label": "ehars_uid"
  },
  "cur_city_name": {
    "type": "String",
    "label": "cur_city_name"
  },
  "cur_county_name": {
    "type": "String",
    "label": "cur_county_name"
  },
  "cur_state_cd": {
    "type": "String"
  },
  "hiv_aids_dx_dt": {
    "type": "Date",
    "label": "hiv_aids_dx_dt"
  }
```

and a patient attribute json with `-a` formatted like

```
[
  {
    "cur_city_name": "Los Angeles",
    "cur_state_cd": "California",
    "hiv_aids_dx_dt": "2008-05-29T07:00:00.000Z",
    "vl_recent_value": "71341",
    "vital_status": "Missing",
    "ehars_uid": "GA00HHARS001056*",
    "rsd_state_cd": "California",
    "race": "Hispanic/Latino",
    "trans_categ": "Missing"
  },
  {
    "cur_city_name": "Los Angeles",
    "cur_state_cd": "California",
    "hiv_aids_dx_dt": "2008-08-08T07:00:00.000Z",
    "vl_recent_value": "0",
    "vital_status": "Missing",
    "ehars_uid": "GA00HHARS005262*",
    "rsd_state_cd": "California",
    "race": "White",
    "trans_categ": "Heterosexual Contact-Female"
  }
]
```

Best,
Steven

**Comment by Omnipotent32** [comment]
> Dear @Omnipotent32,
> 
> There are two portions of the output JSON you may want to verify are being populated.
> 
> For example, in example.json, you need to see something like this:
> 
> ```
>     "patient_attribute_schema": {
>       "_id": {
>         "type": "ObjectID"
>       },
>       "age": {
>         "label": "age",
>         "type": "String"
>       },
>       "birth_sex": {
>         "enum": ["Male", "Female", "", "Missing"],
>         "label": "sex",
>         "type": "String"
>       },
>       "cur_city_fips": {
>         "label": "cur_city_fips",
>         "type": "String"
>       },
>       "cur_city_name": {
>         "label": "cur_city_name",
>         "type": "String"
>       },
>       "cur_county_fips": {
>         "label": "cur_county_fips",
>         "type": "String"
>       },
>       "cur_county_name": {
>         "label": "cur_county_name",
>         "type": "String"
>       },
>       "cur_state_cd": {
>         "label": "cur_state_cd",
>         "type": "String"
>       },
>       "ehars_uid": {
>         "label": "ehars_uid",
>         "type": "String"
>       },
>       "hiv_aids_dx_dt": {
>         "label": "hiv_aids_dx_dt",
>         "type": "Date"
>       },
>       "race": {
>         "enum": [
>           "Native Hawaiian/Other Pacific Islander",
>           "American Indian/Alaska Native",
>           "Other",
>           "Asian",
>           "Black/African American",
>           "White",
>           "Hispanic/Latino",
>           "Multiple Races",
>           "Unknown",
>           "",
>           "Missing"
>         ],
>         "label": "race_cat",
>         "type": "String"
>       },
>       "rsd_county_fips": {
>         "label": "rsd_county_fips",
>         "type": "String"
>       },
>       "rsd_county_name": {
>         "label": "rsd_county_name",
>         "type": "String"
>       },
>       "rsd_state_cd": {
>         "label": "rsd_state_cd",
>         "type": "String"
>       },
>       "sample_dt": {
>         "label": "sample_dt",
>         "type": "Date"
>       },
>       "starhs": {
>         "enum": ["1-AIDS0", "5-MISSING", "", "Missing"],
>         "label": "starhs",
>         "type": "String"
>       },
>       "trans_categ": {
>         "enum": [
>           "MSM",
>           "IDU-Male",
>           "Heterosexual Contact-Male",
>           "Other-Male",
>           "IDU-Female",
>           "Heterosexual Contact-Female",
>           "Other-Female",
>           "Perinatal",
>           "Other-Child",
>           "",
>           "Missing"
>         ],
>         "label": "sex_trans",
>         "type": "String"
>       },
>       "vital_status": {
>         "enum": ["1-Alive", "2-Dead", "9-Unknown", "", "Missing"],
>         "label": "vital_status",
>         "type": "String"
>       },
>       "vl_recent_dt": {
>         "label": "vl_recent_dt",
>         "type": "Date"
>       },
> 
>       "result_interpretation": {
>         "label": "result_interpretation",
>         "type": "String",
>         "enum": ["=", "<", ">", "Missing"]
>       },
> 
>       "vl_recent_value": {
>         "label": "vl_recent_value",
>         "type": "Number"
>       }
>     }
>   }
> ```
> 
> Then, for each node, an example like the following:
> 
> ```
>    {
>         "attributes": [],
>         "baseline": null,
>         "cluster": null,
>         "edi": null,
>         "id": "GA00S000165129-0",
>         "patient_attributes": {
>           "_id": "5845cf134c554ab1d9657dfc",
>           "age": "20-29",
>           "birth_sex": "",
>           "cur_city_fips": "04000",
>           "cur_city_name": "ATLANTA",
>           "cur_county_fips": "089",
>           "cur_county_name": "DEKALB CO.",
>           "cur_state_cd": "Georgia",
>           "ehars_uid": "GA00S000165129-0",
>           "hiv_aids_dx_dt": "1970-01-01T05:35:41.031Z",
>           "race": "",
>           "rsd_state_cd": "Georgia",
>           "sample_dt": "2016-08-08T07:00:00.000Z",
>           "starhs": "",
>           "trans_categ": "",
>           "vital_status": "1-Alive",
>           "vl_recent_value": 453,
>           "result_interpretation": "="
>         }
>       }
> ```
> 
> To do this programmatically, you need to use the `-g` argument to pass a patient_attribute_schema.json file formatted like
> 
> ```
> {
>   "age": {
>     "type": "String",
>     "label": "age_dx"
>   },
>   "ehars_uid": {
>     "type": "String",
>     "label": "ehars_uid"
>   },
>   "cur_city_name": {
>     "type": "String",
>     "label": "cur_city_name"
>   },
>   "cur_county_name": {
>     "type": "String",
>     "label": "cur_county_name"
>   },
>   "cur_state_cd": {
>     "type": "String"
>   },
>   "hiv_aids_dx_dt": {
>     "type": "Date",
>     "label": "hiv_aids_dx_dt"
>   }
> ```
> 
> and a patient attribute json with `-a` formatted like
> 
> ```
> [
>   {
>     "cur_city_name": "Los Angeles",
>     "cur_state_cd": "California",
>     "hiv_aids_dx_dt": "2008-05-29T07:00:00.000Z",
>     "vl_recent_value": "71341",
>     "vital_status": "Missing",
>     "ehars_uid": "GA00HHARS001056*",
>     "rsd_state_cd": "California",
>     "race": "Hispanic/Latino",
>     "trans_categ": "Missing"
>   },
>   {
>     "cur_city_name": "Los Angeles",
>     "cur_state_cd": "California",
>     "hiv_aids_dx_dt": "2008-08-08T07:00:00.000Z",
>     "vl_recent_value": "0",
>     "vital_status": "Missing",
>     "ehars_uid": "GA00HHARS005262*",
>     "rsd_state_cd": "California",
>     "race": "White",
>     "trans_categ": "Heterosexual Contact-Female"
>   }
> ]
> ```
> 
> Best,
> Steven

Thank you, dear Steven! I'm going to have a try!
Best,
Omnipotent32
