### ISSUE TITLE
Webapplication always loading

### ISSUE THREAD

**Issue by caggtaagtat** [veg/hivtrace-viz#74]
Hi,
the webpage of hivtrave viz seems to not load anymore. It only shows the message "Loading network" and you can't click anything.

**Comment by stevenweaver** [comment]
Dear @caggtaagtat, 

Which browser and operating system are you using?

Best,
Steven

**Comment by stevenweaver** [comment]
Dear @caggtaagtat, 

I see now. https://veg.github.io/hivtrace-viz/ is not functional. While this issue is being resolved, feel free to try http://demo.hivtrace.org/network.html or installing the package locally. 

```
git clone https://github.com/veg/hivtrace-viz.git
cd hivtrace-viz
yarn
webpack
yarn develop
```

Best,
Steven

**Comment by caggtaagtat** [comment]
Thank you very much for the demo link.
Kind regards,
Johannes
