### ISSUE TITLE
How to use the hivtrace-viz package

### ISSUE THREAD

**Issue by shaodi711** [veg/hivtrace-viz#75]
Dear stevenweaver,
Sorry for disturbing you. I'm very interested in HIV-TRACE. I want to visualize the “. json” results of HIV-TRACE. And I have installed the hivtrace-viz package locally. However, I don’t know how to use this package for visual analysis? Could you give me an example to show it?
Best regards!

**Comment by stevenweaver** [comment]
Dear @shaodi711, 

Sorry, this issue slipped past me. Please follow the instructions for Development, https://github.com/veg/hivtrace-viz#development. 

When you navigate to your local instance, you should see a `File` dropdown menu, and you can load the JSON results there. 

I did create a command line tool that will also spawn hivtrace-viz with a supplied JSON argument, if that is what you are looking for?

Best,
Steven
