### ISSUE TITLE
Attribute proportions (pie chart visualizations) are not visible from "cluster zoom" view

### ISSUE THREAD

**Issue by stevenweaver** [veg/hivtrace-viz#9]
<img width="1221" alt="screen shot 2018-01-08 at 12 16 11 pm" src="https://user-images.githubusercontent.com/535261/34690409-de87c5a6-f46d-11e7-8bd9-023ef698ae92.png">

**Comment by spond** [comment]
Dear @stevenweaver,

I have identified the issue causing this bug. A proper solution will require some additional engineering to properly pass state variables between instances of network rendering. I'll implement it together with the "single cluster" view for the main panel.

Best,
Sergei

**Comment by spond** [comment]
Closing because this issue is resolved in the new "tab" view of individual clusters.
